ekgxml:
  collector:
    path: /sample/ES_ERROR_FILE
    logPath: ekgLog
    retry: false
  csv:
    path: /sample/ES_ERROR_FILE
    outputPath: /sample/ES_ERROR_FILE_out
    converter: standalone/csv.exe
    awsS3:
      endPoint: https://localhost
      regionName: localhost
      accessKey: accessKey
      secretKey: secretKey
      bucketName: testBucket
  uploader:
    host: https://localhost
    svmUUID: svmUUID
    bucketName: test
    bucketUUID: bucketUUID
    userName: test
    password: test
  es:
    bulkSize: 100
    userName: elastic
    password: elastic
    host: 127.0.0.1
    port: 9200
    indexName: test
    settingsLocation: standalone/settings.json
    mappingsLocation: standalone/mappings.json
  datasource:
    local:
      url: jdbc:sqlite:ekgxml.db
      driver-class-name: org.sqlite.JDBC
    external:
      url: jdbc:sqlserver://172.31.119.11:1433;databaseName=HISDW;encrypt=true;trustServerCertificate=true
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: fpahsqkek
      initialSize: 0
      maxTotal: 10
      maxIdle: 10
      minIdle: 0
