ekgxml:
  collector:
    path: D:/ekgsample
    logPath: ekgLog
    datasource:
      url: jdbc:sqlserver://172.31.119.11:1433;databaseName=HISDW;encrypt=true;trustServerCertificate=true
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: fpahsqkek
      initialSize: 0
      maxTotal: 10
      maxIdle: 10
      minIdle: 0
  csv:
    path: D:/ekgsample
    outputPath: D:/ekgsample/out
    converter: standalone/csv.exe
    awsS3:
      endPoint: https://localhost
      regionName: localhost
      accessKey: accessKey
      secretKey: secretKey
      bucketName: testBucket