# Spring Profile
spring:
  profiles:
    active: prod

ekgxml:
  collector:        # Collector
    path: D:/ekgsample
    logPath: ekgLog
    datasource:
      url: jdbc:sqlserver://192.168.0.22:1433;databaseName=testdb;encrypt=true;trustServerCertificate=true
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: 1111
      initialSize: 0
      maxTotal: 10
      maxIdle: 10
      minIdle: 0
  csv:              # CSV
    path: /sample/2022
    outputPath: /sample/2022_out
    converter: standalone/csv
    awsS3:
      endPoint: https://localhost
      regionName: localhost
      accessKey: accessKey
      secretKey: secretKey
      bucketName: testBucket
logging:            # Logback
  config: standalone/logback-spring-standalone.xml