# Spring Profile
spring:
  profiles:
    active: prod

ekgxml:datasource:
  destination: # destination
    url: jdbc:sqlserver://192.168.137.73:1433;databaseName=HISDW2;encrypt=true;trustServerCertificate=true
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: fpahsqkek
    maximum-pool-size: 10
  transformation: # transformation
    url: jdbc:sqlserver://192.168.137.73:1433;databaseName=HISDW;encrypt=true;trustServerCertificate=true
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: fpahsqkek
    maximum-pool-size: 10
  collector:        # Collector
    path: D:/ekgsample
    logPath: ekgLog
    loadTableName: RESTING_ECG

  csv:              # CSV
    path: D:/ekgsample
    outputPath: D:/ekgsample/out
    converter: standalone/csv
    awsS3:
      endPoint: https://localhost
      regionName: localhost
      accessKey: accessKey
      secretKey: secretKey
      bucketName: testBucket
logging:            # Logback
  config: standalone/logback-spring-standalone.xml